### ISSUE TITLE
Number always one behind

### ISSUE THREAD

**Issue by rafiwui** [nandee95/CMake-Automatic-Build-Number-Increment#1]
Is it intended or not possible to have the correct build number when the program is running?
The build number is incremented correctly but your example (and my program) are both showing the previous number.

**Comment by rafiwui** [comment]
If you replace `add_custom_command' with ' add_custom_target' so it looks sth like this:
```
add_custom_target(
	version
	COMMAND ${CMAKE_COMMAND}
		-DLANGUAGE:STRING="C"
		-DHEADER_DIR:PATH="${CMAKE_SOURCE_DIR}"
		-DCACHE_DIR:PATH="${CMAKE_CURRENT_BINARY_DIR}${CMAKE_FILES_DIRECTORY}"
		-P "${MASTER_DIR}/build_number.cmake"
)
```
**AND** you add this line after this codeblock:
```
add_dependencies(project_name_goes_here version)
```
Then it will work flawless.

**Comment by nandee95** [comment]
Sorry for the late reply, my CMake was broken back then.
The first build gets the number 1 as intended, I don't think there is anything wrong with it.
